const stateActionTypes = {
    GET_COVID_DATA_STATE_WISE: 'GET_COVID_DATA_STATE_WISE',
    SET_COVID_DATA_STATE_WISE: 'SET_COVID_DATA_STATE_WISE',
    GET_CASES_TIME_SERIES : 'GET_CASES_TIME_SERIES',
}

export default stateActionTypes;